### ISSUE TITLE
The errors don't work.

### ISSUE THREAD

**Issue by RufusMeatBoot** [craftablescience/ChiraLang#1]
So I did some testing, and the errors don't seem to work. For example, when calling a non-existent variable, there are no errors. I'm not sure if this is a discontinued project, so this might be a useless issue.

**Comment by craftablescience** [comment]
This entire thing is a work in progress, it's all horribly broken. If you want to fix it, that would be lovely, but I'm really busy with some other things at the moment. I made this in about 6 hours so it shouldn't be too difficult.

**Comment by RufusMeatBoot** [comment]
Ok. I might, as I think this whole project is really cool.

**Comment by craftablescience** [comment]
lol closing because I'm never touching this again
